# /etc/zsh/zshrc

[[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && \
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && \
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '%F{yellow}!%f'
zstyle ':vcs_info:git:*' stagedstr '%F{cyan}+%f'
zstyle ':vcs_info:git:*' formats '(%F{magenta}%b%f%u%c) '
zstyle ':vcs_info:git:*' actionformats '(%F{magenta}%b%f|%F{red}%a%f%u%c) '

precmd() { vcs_info }

autoload -Uz colors && colors
# Green for user, Red for root
USER_COLOR="%F{green}"
[[ $UID -eq 0 ]] && USER_COLOR="%F{red}"

PROMPT='${USER_COLOR}%n@%m%f:%F{blue}%~%f ${vcs_info_msg_0_}${USER_COLOR}%#%f '

HISTFILE="$XDG_DATA_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=10000
# Ensure directory exists
[[ ! -d "$(dirname "$HISTFILE")" ]] && mkdir -p "$(dirname "$HISTFILE")"

autoload -Uz compinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"

alias ls='ls --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'
